name: CI/CD Pipeline From Dev to Prod Frontend
on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm install

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   needs: sonarqube
  #   name: Build and Deploy
  #   steps:
  #     - name: Clone Source Code
  #       uses: actions/checkout@v4

  #     - name: Build Docker Image
  #       run: |
  #         docker build -t ${{ env.DOCKER_IMAGE_NAME }} .

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Build Application
  #       run: npm run build

  #     - name: Deploy to Production
  #       uses: easingthemes/ssh-deploy@v2.1.5
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         ARGS: "-rltgoDzvO --delete"
  #         SOURCE: "build/"
  #         REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  #         REMOTE_USER: ${{ secrets.REMOTE_USER }}
  #         TARGET: ${{ secrets.REMOTE_PATH }}
